[book]
authors = ["Evan Pratten"]
language = "en"
multilingual = false
src = "docs/book"
title = "Protomask Documentation"

[rust]
edition = "2021"

[build]
build-dir = "target/book"
create-missing = true

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/ewpratten/protomask"
site-url = "/book/"
additional-js = ["docs/book/mermaid/mermaid.min.js", "docs/book/mermaid/mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
