[book]
authors = ["Evan Pratten"]
language = "en"
multilingual = false
src = "docs/book"
title = "Protomask Documentation"

[rust]
edition = "2021"

[build]
build-dir = "target/book"
create-missing = true

[output.html]
mathjax-support = true