[package]
name = "<crate_name>"
version = "0.1.0"
authors = ["Evan Pratten <ewpratten@gmail.com>"]
edition = "2021"
description = "<description>"
documentation = "https://docs.rs/<crate_name>"
readme = "README.md"
homepage = "https://github.com/ewpratten/<repo_name>"
repository = "https://github.com/ewpratten/<repo_name>"
license = "GPL-3.0"
keywords = []
categories = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "<crate_name>"
path = "src/main.rs"

