# Example configuration file for protomask
[Interface]
# Addresses to use for ICMP messaging
Address4 = "192.0.2.1"
Address6 = "2001:db8:1::1"
# A list of IPv4 prefixes to NAT to
Pool = ["192.0.2.0/24"]
# The IPv6 prefix to listen for traffic on
Prefix = "64:ff9b::/96"

[Rules]
# A static mapping of IPv4 and IPv6 addresses
# These addresses will be exclusively reserved, and not used in the general pool
MapStatic = [{ v4 = "192.0.2.2", v6 = "2001:db8:1::2" }]
