[toolchain]
channel = "nightly-2023-07-26"
# components = [
#     "cargo",
#     "clippy",
#     "rust-docs",
#     "rust-src",
#     "rust-std",
#     "rustc",
#     "rustfmt",
# ]
# targets = [
#     "bpfel-unknown-none",
#     "bpfeb-unknown-none",
# ]
