name: Build

on:
  pull_request:
  push:
    paths: 
      - '.github/workflows/build.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/src/*'

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release