name: Documentation

on:
  pull_request:
  push:
    paths:
        - ".github/workflows/docs.yml"
        - "docs/**"
        - "book.toml"

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Build Book
        run: mdbook build

      - name: Build Website
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_DIR: ./docs/website
          BUILD_ONLY: true
