name: Documentation

on:
  pull_request:
  push:
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
      - "book.toml"

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Build Book
        run: mdbook build

      - name: Build Website
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_DIR: ./docs/website
          BUILD_ONLY: true

      - name: Combine Book and Website
        run: mkdir -p /tmp/combined && cp -rv docs/website/public/* /tmp/combined && cp -rv target/book/ /tmp/combined/book

      - name: Write CNAME file
        run: echo "protomask.ewpratten.com" > /tmp/combined/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: /tmp/combined

      - name: Deploy
        uses: actions/deploy-pages@v2
        id: deployment
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/ewpratten/reorg2' }}
